name: Build

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Kuper
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean assembleDebug --full-stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: YouShade-Debug
          path: Kuper/app/build/outputs/apk/debug/*.apk
